# Site
repository: femijoshuao/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: Femi Joshua O
title: IT Solution Developer | System Administrator
email: femi-joshua@ichanneltech.com
website: https://ichanneltech.com

# Social links
twitter_username: femijoshuao
facebook_username: femijoshuao
instagram_username: femijoshuao
linkedin_username: femijoshuao
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/femijoshuao

# About Section
# about_title: About Me
about_profile_image: images/fm1.png
about_content: |
  Hello, my name is Femi Joshua Olayiwola. I am a Technocrat, Social Entrepreneur, Realist, and Gospel Advocate. 
  I work with IChannel Technologies in Nigeria as a senior executive director. 
  In practice, I work as a solutions developer, designing programs, software, and network architecture to meet the needs of my clients. 
  I help my clients reach their objectives by developing IT solutions that address all of their requirements. 
  I've worked for a lot of firms, earning experience in teamwork and leadership.

  I am most skilled in Cloud services administration and <mark>eating pizza</mark> ðŸ•.

content:
  - title: Projects # Title for the section
    layout: list
    content:
      - layout: left
        border: weak
        title: ERP Solutions with ERPNext
        link: 
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/frappe/erpnext
        quote: >
          ERPNext is one of the most impressive enterprise business applications on which I have ever worked. 
          Because it is a Phyton application and an open source project, its simplicity and community of talented developers 
          assist in promptly resolving issues..
        description: |
        I've been working on ERPNext for over six years and have implemented it in a variety of businesses.
          This project began as a way for me to understand the Frappe Framework and to assist my customers in moving to a 
          digital business application in order to achieve their objectives. Frappe framework has taught me a lot of useful skills, and I'm pleased to have it in my portfolio.
          If you're looking for a cost-effective business application that can replace SAP or SAGE and includes manageable modules such as Accounting, 
          Invoicing, Inventory, Manufacturing, Sales, Human Resources, and more, go no further. I'll gladly help you set it up on any cloud service 
          provider of your choosing. I also provided a managed solution for small businesses.
      - layout: left
        title: Bizsuite BMS
        link: bizsuite.com.ng
        additional_links:
          - title: Business Management Application
            icon: fa fa-chrome
            url: https://bizsuite.com.ng
        quote: >
          Powerful Business Management System, and 'Apps for SMEs'.
        description: |
          BizSuite BMS is forked business management software focused on simplicity. I believe that the best software is the one that is easy to use, 
          and this is what I strive for with our software. With an intuitive user interface and with no complicated tasks, 
          BizSuite is perfect for any small business or freelancer. It comes with extend functionalities and adaptive modules that suit your business, BizSuite comes with a lifetime development and integration cycle; 
          new version releases and updates
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: IChannel Technologies
        sub_title: Senior Executive Officer
        caption: Nov 2010 - Present
        link: https://ichanneltech.com
        description: |
          I take a leading position in the development, execution, monitoring, and management of projects, as well as their conclusion. 
          I design and implement custom IT solutions that meet the needs of my customers' businesses. 
          I also take care of the many administrative tasks that go along with a project. 

      - layout: left
        border: weak
        title: Ideal Konsult
        sub_title: Network Administrator / Trainer
        caption: March 2009
        description: |
          Instruct Cisco , Microsoft, Security and System Administration Courses
          - Developed Cisco and Microsoft training curriculum for Idea Konsult IT Training Center
          - Managing the networking system and ensuring adequate network security
          - Site Technician for Pearson VUE and Thomson Prometric Testing Center
  - title: Capabilities and skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Understand the country information and technology communication business strategies
      - Open Minded, the ability to understand, handle any new technologies in a short time
      - Providing expedient error corrections and solutions whilst working on projects in a variety of support and development roles.
      - Highly Intellectual in use of Computer and well experienced in using most application and system software
      - Excellent in website and web application designing using content management 
      - Understanding Complex network, such as IP, IGRP, IP RIP, asynchronous routing, Apple Talk, Extended 
      access-list, route redistribution, IPX RIP, route summarization, OSPF, VLSM, Serial IGRP, VLAN, Ethernet access-list 802.10
      - Technically skilled in Remote Troubleshooting
      - Exceptional skill in the use and deployement of Open source software
      -  Able to work on <mark>Switches</mark> (Cisco, Mikrotik, AirLive), <mark>Routers</mark> (Cisco, Mikrotik, Ubiquiti), Wireless Equipment (Cisco, Ubiquiti, Mikrotik Cisco PIX Firewall

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
